
result <- c(
    "bankruptcy",
    "big failure",
    "bitter disappointment",
    "blunder",
    "bomb",
    "bust",
    "calamity",
    "car crash",
    "cataclysm",
    "catastrophe",
    "clunker",
    "clusterfuck",
    "cock-up",
    "complete failure",
    "crevasse of despair",
    "damp squib",
    "dead loss",
    "defeat",
    "debacle",
    "disappointment",
    "disaster",
    "dismal failure",
    "dog's breakfast",
    "dud",
    "dumpster fire",
    "embarrassment",
    "epic fail",
    "fiasco",
    "fine kettle of fish",
    "fizzle",
    "flash in the pan",
    "flop",
    "flopperoo",
    "fright",
    "foul-up",
    "fuckup",
    "gaffe",
    "glitch",
    "grave error",
    "heap",
    "howler",
    "imbroglio",
    "job unwell done",
    "lack of success",
    "lead balloon",
    "lemon",
    "letdown",
    "massacre of intelligence",
    "mess",
    "mire",
    "misadventure",
    "misfiring",
    "mishap",
    "mistake",
    "mix-up",
    "monumental failure",
    "muck-up",
    "negative outcome",
    "non-starter",
    "nonevent",
    "nonperformance",
    "nonsuccess",
    "pickle",
    "pile of garbage",
    "puddle of vomit",
    "predicament",
    "problem",
    "quagmire",
    "rubbish dump",
    "sack of shit",
    "screw-up",
    "setback",
    "shamble",
    "shemozzle",
    "shitshow",
    "slipshod piece of work",
    "snafu",
    "unpleasant situation",
    "total disaster",
    "tragedy",
    "train wreck",
    "turkey",
    "utter disappointment",
    "washout",
    "waste of time",
    "wreck"
);
