
created <- c(
  "abused",
  "assembled (without plan)",
  "created (with poor knowledge)",
  "befouled",
  "botched",
  "brewed",
  "bungled",
  "built (without cause)",
  "composed (without skills)",
  "constructed (for no readily apparent purpose)",
  "designed (without style)",
  "destroyed",
  "devastated",
  "devised (without coherence)",
  "disordered",
  "disorganized",
  "fluffed",
  "forged",
  "formed (with neglect)",
  "fucked up",
  "fumbled",
  "hacked",
  "harmed",
  "hurt",
  "ignored",
  "initiated (without forethought)",
  "made (for who knows what reason)",
  "mangled",
  "marred",
  "misdirected",
  "misgoverned",
  "mishandled",
  "mismanaged",
  "misused",
  "mucked up",
  "planned (without care)",
  "prepared (without rigour)",
  "ruined",
  "screwed up",
  "set up (with negligence)",
  "spoiled",
  "thrown together",
  "wrecked"
);

creating <- c(
  "abusing",
  "assembling",
  "befouling",
  "botching",
  "brewing (without forethought)",
  "building (without care)",
  "bungling",
  "composing (without due care)",
  "constructing (without foresight)",
  "designing (with neglect)",
  "destroying",
  "devastating",
  "devising (without precaution)",
  "disordering",
  "disorganizing",
  "forging",
  "forming (sans intelligence)",
  "fucking up",
  "fumbling",
  "hacking",
  "harming",
  "hurting",
  "ignoring",
  "initiating (without cause)",
  "making (without care)",
  "mangling",
  "marring",
  "misdirecting",
  "misgoverning",
  "mishandling",
  "mismanaging",
  "misusing",
  "mucking up",
  "planning (without skill)",
  "preparing (without circumspection)",
  "ruining",
  "screwing up",
  "setting up (for failure)",
  "spoiling",
  "wrecking"
);
